### ISSUE TITLE
Unknown tag !LuaMap

### ISSUE THREAD

**Issue by Jing-Lee-tj** [SeisSol/easi#45]
Hi! When I run SeisSol, I encountered a program error 
`fault.yaml: yaml-cpp: error at line 1, column 1: Unknown tag! LuaMap`
I found something about LuaMap in the Example folder, but it seems to be Functionmap in the easi document. Is Luamap replaced by functionmap?

**Comment by Thomas-Ulrich** [comment]
Hi, 
You need to recompile easi with Lua support (did you compile with spack?)

Le 15 novembre 2023 20:30:05 GMT+01:00, Jing Li ***@***.***> a écrit :
