### ISSUE TITLE
ASAGI block in a !EvalModel

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/easi#9]
Hi,
This is more a question than an issue.
If I have a netcdf containing an array of structure (list) [rho, mu, lambda], how can I use the mu  parameter of ASAGI as an input to a !FunctionMap.
I tried:
```
[plastCo]: !EvalModel
        parameters: [rho, mu, lambda]
        model: !ASAGI
           file: mynetcdf.nc
           parameters: [rho, mu, lambda]
           var: data
        components: !FunctionMap
          map:
             plastCo: return mu*0.0001;
```
But got:
```
cvmh1000m_material_Plastic_gamma085.yaml: yaml-cpp: error at line 31, column 16: : ASAGI supplies 1D output (got lambda,mu,rho).

**Comment by uphoffc** [comment]
Could you maybe append ncdump -h mynetcdf.nc?

**Comment by Thomas-Ulrich** [comment]
```
netcdf Ridgecrest_RhoMuLambda_1000 {
types:
  compound material {
    float rho ;
    float mu ;
    float lambda ;
  }; // material
dimensions:
	x = 205 ;
	y = 203 ;
	z = 111 ;
variables:
	float x(x) ;
	float y(y) ;
	float z(z) ;
	material data(z, y, x) ;
}
```

**Comment by uphoffc** [comment]
Hmm.. the easi file and the Netcdf file look fine. Not sure what the problem is...
Error stems from https://github.com/SeisSol/easi/blob/master/include/easi/component/ASAGI.h#L110

**Comment by Thomas-Ulrich** [comment]
grid->getVarSize() = sizeof(float)= 4.

**Comment by uphoffc** [comment]
Yes, but getVarSize() should return the size of material which should be 12.

**Comment by Thomas-Ulrich** [comment]
Hi,
Any idea of a workaround (other than not using structures?).
I tried this (assuming the error in only in the getVarSize function of ASAGI: 
```
m_numValues = dimCodomain();
  //m_numValues = grid->getVarSize() / sizeof(float);
```
And it works for accessing rho, but not for accessing mu and lambda in the FunctionMap (which return 0). Therefore it seems the error is not limited to getVarSize.

**Comment by uphoffc** [comment]
Can you send me the send me the yaml file and the netcdf file for debugging?

**Comment by Thomas-Ulrich** [comment]
I was preparing the setup for you to debug and realized that actually I made a mistake...
Actually, the file that I was testing is a bit more complex than the one I 've shown (but I just showed the piece which was raising me the error).
I now I realize that there are  2 ASAGI blocks in the file (one with a structure, another with a float) and I swapped the filenames ....
Sorry about that, the problem is solved then!
